name: Deploy to Azure Container App

permissions:
  contents: read
  packages: write


on:
  workflow_dispatch:


env:
  RESOURCE_GROUP: acmetickets_rg
  CONTAINERAPPS_ENVIRONMENT: acmeticketsacadev
  AZURE_LOCATION: eastus
  IMAGE_NAME: acmetickets-api
  REGISTRY: ghcr.io
  APP_NAME: acmetickets-api

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Get GitHub App Token
      id: app-token
      uses: tibdex/github-app-token@v2
      with:
        app_id: ${{ secrets.GH_APP_ID }}
        private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}

    - name: Build and push Docker image to GHCR
      run: |
        IMAGE_TAG=$(echo "ghcr.io/${{ github.repository }}/api:${{ github.sha }}" | tr '[:upper:]' '[:lower:]')
        echo $IMAGE_TAG
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        docker build -t $IMAGE_TAG -f src/Message/Dockerfile .
        docker push $IMAGE_TAG
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

    - name: Check if Azure Container App exists
      id: check_aca
      run: |
        if az containerapp show --name "$APP_NAME" --resource-group "$RESOURCE_GROUP" > /dev/null 2>&1; then
          echo "exists=true" >> $GITHUB_OUTPUT
        else
          echo "exists=false" >> $GITHUB_OUTPUT
        fi

    - name: Validate token access to GHCR
      run: |
        curl -v -H "Authorization: Bearer ${{ steps.app-token.outputs.token }}" \
        https://ghcr.io/v2/acmetickets/eventmanagement/api/tags/list

    - name: Create Container App (if not exists)
      if: steps.check_aca.outputs.exists == 'false'
      run: |
        az containerapp create \
          --name "$APP_NAME" \
          --resource-group "$RESOURCE_GROUP" \
          --environment "$CONTAINERAPPS_ENVIRONMENT" \
          --image "$IMAGE_TAG" \
          --registry-server ghcr.io \
          --registry-username x-access-token \
          --registry-password "${{ steps.app-token.outputs.token }}" \
          --ingress external \
          --target-port 5271 \
          --cpu 0.5 --memory 1.0Gi \
          --env-vars ASPNETCORE_ENVIRONMENT=Development ConnectionStrings__AzureServiceBus=${{ secrets.AZURE_SERVICEBUS_CONNECTION_STRING }}

    - name: Set registry credentials (for updates)
      if: steps.check_aca.outputs.exists == 'true'
      run: |
        az containerapp registry set \
          --name "$APP_NAME" \
          --resource-group "$RESOURCE_GROUP" \
          --server ghcr.io \
          --username x-access-token \
          --password "${{ steps.app-token.outputs.token }}"

    - name: Update Container App with new image
      if: steps.check_aca.outputs.exists == 'true'
      run: |
        az containerapp update \
          --name "$APP_NAME" \
          --resource-group "$RESOURCE_GROUP" \
          --image "$IMAGE_TAG"
